### PR TITLE
Adding POWER(ppc64le) architecture support

### PR DESCRIPTION
**Pull request by bahetiamit**
This change adds the support for POWER (ppc64le) architecture to the image. This was tested on master branch in travis. This is an extension to https://github.com/alpine-docker/git/pull/23

### CODE REVIEW

**Comment by barthy1** [comment]
Hi @bahetiamit ! Thank you for this PR. 
Could you please share Travis build logs and link to the multi-arch image you got after the build?

**Comment by bahetiamit** [comment]
@barthy1 

Please find the travis logs at - https://travis-ci.org/github/bahetiamit/git/builds/729545845 and travis built images at - https://hub.docker.com/repository/registry-1.docker.io/bahetiamit/git/tags?page=1

**Comment by barthy1** [comment]
hey @ozbillwang 
I've verified that proposed code adds `ppc64le` arch to multi-arch `apline/git` images.
I also verified that resulted ppc64le image is buildable and runnable for according arch. No changes are introduced for s390x or amd64 builds. 

Are you ok to merge this code?

**Comment by ozbillwang** [comment]
Thanks, @barthy1 

I am fine for the change. Let's merge it.

Please confirm if you can merge it directly.

**Comment by snehlatamohite** [comment]
@bahetiamit @barthy1 - Thanks for working on this.

**Pull request merged**
