### PR TITLE
removed the container to run as root and added a user

### PR DESCRIPTION
**Pull request by vikas027**
also, updated the LABEL field with the recommend key-value pair syntax

This also helps to run the image on k8s clusters which do not allow to run containers with root user. Also, recommended by [docker](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user)

Signed-off-by: Vikas Kumar <vikas@reachvikas.com>

### CODE REVIEW

**Comment by ozbillwang** [comment]
Thanks, @vikas027 . 

Since most official docker images are running as root (such as python, node), I would not merge this PR. 

I have created a new feature branch called `feature/non-root`, we can build a new tag as `alpine/git:<version>-nonroot` and `alpine/git:non-root` as latest one. 

Please change your PR accordingly.

**Comment by vikas027** [comment]
> Thanks, @vikas027 .
>
> I have created a new feature branch called `feature/non-root`, we can build a new tag as `alpine/git:<version>-nonroot` and `alpine/git:nonroot` as latest one.
> 
> Please change your PR accordingly.

Sure, sounds good. I have updated the PR.

**Comment by ozbillwang** [comment]
>Not sure why the build has failed while waiting for a password.

i have fixed this issue with #20 , if you rebase (merge) from master , you should get the check passed.

**Comment by vikas027** [comment]
> > Not sure why the build has failed while waiting for a password.
> 
> i have fixed this issue with #20 , if you rebase (merge) from master , you should get the build check passed.

Nice! All green now.

**Comment by ozbillwang** [comment]
two new tags are created

```
alpine/git:<version>-user
alpine/git:user
```
image

**Pull request merged**
